name: simple action
on: [push]
jobs:
  clone-repo-for-build:
    run-on: ubuntu-latest
    steps:
      - user: actions/checkout@v3
      - user: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install 
      - run: |
          npm -v
          
